[package]
name = "server"
version = "0.1.0"
authors = ["neil399399 <neil399399@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

#crate
httpapi = {path = "../httpapi"}