version: "3"

networks:
  local:

services:
  postgres:
    image: postgres:11-alpine
    container_name: rust_api_postgres
    expose:
      - ${PGPORT}/tcp
    ports:
      - ${PGPORT}:5432
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
    networks:
      - local

  adminer:
    image: adminer:latest
    container_name: rust_api_adminer
    ports:
      - ${ADMINER_PORT}:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    networks:
      - local
